site_name: ğŸ“Š API RESTful com AutenticaÃ§Ã£o JWT e Scraping de Dados da B3
site_url: https://fernandoko3lle.github.io/Cloud_OpenStack
use_directory_urls: false
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
docs_dir: docs
nav:
  - ğŸ“Š Overview: index.md
  - ğŸ“¤ PublicaÃ§Ã£o no Docker Hub: dockerhub.md
  - âš™ï¸ Docker Compose: compose.md 
  - ğŸ’» Como rodar localmente: Rodando_Localmente.md
  - ğŸ“¸ UlitizaÃ§Ã£o: utilizacao.md
  - ğŸ›¡ï¸ Seguranca e Arquitetura : seguranca.md



