site_name: Cloud
site_url: https://fernandoko3lle.github.io/Cloud_OpenStack
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections   # separa cada item de topo em â€œseÃ§Ãµesâ€ na sidebar
    #- navigation.expand  
    - navigation.instant
    - navigation.instant.progress
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
docs_dir: docs
nav: 
  - index.md
  - MaaS: 
    - Relatorio: maas/relatorio.md
  - JUJU: 
    - Relatorio: juju/main.md
  - OpenStack:
    - ğŸ¯ objetivo: open/objetivo.md
    - Criando a Infraestrutura: 
      - ğŸ”Œ Deployment e IntegraÃ§Ã£o: open/infra.md
      - ğŸ” Vault + Certificado CA: open/vault.md
      - âœ… VerificaÃ§Ã£o do Estado: open/status.md
    - Configurando o Openstack:
      -  ğŸ› ï¸ ConfiguraÃ§Ã£o Inicial: open/config_ini.md
      - ğŸ–¼ï¸ Criando Imagens e Flavors: open/img_flavor.md
      - ğŸ”€ Redes + Roteador: open/rede_roteador.md
      - ğŸ”’ ConexÃ£o e SeguranÃ§a: open/conex_seg.md
      - ğŸš€ LanÃ§amento de InstÃ¢ncias: open/instancias.md
      - ğŸ“ˆ Escalabilidade: open/escala.md
    - AplicaÃ§Ã£o no Openstack:
      - ğŸš€ Subindo aplicaÃ§Ã£o: open/subindo_api.md
      - ğŸ“Š ValidaÃ§Ã£o de Flavor: open/desempenho.md
      - ğŸŒ Topologia de Rede: open/topologia.md
      - âš–ï¸ Load Balancer: open/lb.md
  - "SLA, DR e IaC":  
    - SetUp: Iac/setUp.md
    - Terraform: Iac/terraform.md
    - Resultados: Iac/resultados.md
    - Exercicio: Iac/exercicio.md 
  - "DockerizaÃ§Ã£o":
      - ğŸ“Š Overview: api/overview.md
      - ğŸ“¤ PublicaÃ§Ã£o no Docker Hub: api/dockerhub.md
      - âš™ï¸ Docker Compose: api/compose.md 
      - ğŸ’» Como rodar localmente: api/Rodando_Localmente.md
      - ğŸ“¸ UlitizaÃ§Ã£o: api/utilizacao.md
      - ğŸ›¡ï¸ Seguranca e Arquitetura : api/seguranca.md
  - Projeto AWS: 
    - AWS: aws/aws.md
    

